### ISSUE TITLE
how to detect Select item?

### ISSUE THREAD

**Issue by winterlovesong** [daria-kopaliani/DARecycledScrollView#4]
hello

i use method : 
- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath

not work!

help me pls!! Thank you

**Comment by daria-kopaliani** [comment]
Hi winterlovesong,
The metod you are using is declared UITableViewDelegate protocol, that's why it's not working.
In order to detect tap in DATileView you should subclass it and catch and handle touch events there. I would the "delegate" pattern here as well. 
Let me know it you are still struggling with this, then I'll update DARecycledScrollView demo project to have this feature as well.
